#!/usr/bin/env bash
#Bash script that displays a list of currently running process.
# Show all processes, for all users, including those which might not have a TTY.
# Display in a user-oriented format.
ps auxf
