#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
m=1
while [[ $m -le 100 ]]; do
	if (( (m % 3 == 0) && (m % 5 == 0) ))
	then
		echo "FizzBuzz"
	elif (( m % 3 == 0 ))
	then
		echo "Fizz"
	elif (( m % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$m"
	fi
	((m += 1))
done
