#!/usr/bin/env bash
# A Bash script that groups visitors by IP and HTTP status code, and displays this data.# Ordered from the greatest to the lowest number of occurrences
m="apache-access.log"
awk -F' ' '{ print $1, $9}' $m | sort | uniq -c|sort -nr
