#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format: Where only the part of the name after the first dash is displayed
m=$(ls)
for x in $m; do
	echo "$x" | cut -d '-' -f2
done
